version: '3'
services:
  db:
    image: postgres:16
    # volumes:
    #   - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    depends_on:
      - db
    ports:
      - "50051:50051"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_SSLMODE=${POSTGRES_SSLMODE}
      - USE_DATABASE=${USE_DATABASE}
    command: >
      sh -c "./init.sh"

# volumes:
#   db_data:
