version: '3.8'
services:
  db:
    image: postgres:16
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: grpctmp1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: grpctemp
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    depends_on:
      - db
    ports:
      - "50051:50051"
    environment:
      - POSTGRES_DB=grpctmp1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=grpctemp
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_SSLMODE=disable
    command: >
      sh -c "migrate -path ./migrations -database postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB} up && ./main"

volumes:
  db_data:
