package myerror

var (
	PageNotFoundError                      = New(404, "page not found error")
	DotEnvFileError                        = New(500, "dot env file not found error")
	PasswordNotMatched                     = New(401, "password did not matched")
	EmptyRedisValue                        = New(500, "empty redis value")
	EmailVerifyOtpNotMatch                 = New(400, "not a valid otp")
	ExaustRateLimmit                       = New(429, "rate limit exhausted")
	RedisKeyNotFound                       = New(500, "redis key not found")
	ReflectFieldNotFound                   = New(500, "field not found in given struct")
	UnactiveUserError                      = New(401, "user has not verified its email")
	UserIsAlreadyActive                    = New(400, "user is already active, cannot generate otp for verify")
	InvalidAccessToken                     = New(401, "invalid access token")
	TokenExpired                           = New(401, "token is expired")
	ValueConversitionError                 = New(500, "context value conversation error")
	OwnerNotMatchedError                   = New(403, "owner id not matched with user id")
	SQLUniqueViolationError                = New(409, "duplicate key value violates unique constraint")
	BrandAlreadyExists                     = New(409, "brand already exists")
	NotImplementedError                    = New(501, "not implemented error")
	UnauthorizedError                      = New(403, "unauthorized error")
	DBExecNoRowFoundError                  = New(404, "no row found error")
	ZeroCartItemError                      = New(400, "no item is in the cart")
	ErrorUserPaymentMethod                 = New(404, "user payment method not found")
	ErrorOffsetNotValid                    = New(400, "offset is not valid its not multiple of 10")
	ErrorShopDoesNotExists                 = New(400, "shop does not exists")
	ErrorBrandDoesNotExists                = New(400, "brand does not exists")
	ErrorVariationIdRequired               = New(400, "variation id is required")
	ErrorVariationValueRequired            = New(400, "variation value is required")
	ErrorProductDoesNotExists              = New(400, "product does not exists")
	ErrorDuplicateProductItem              = New(400, "duplicate product item cannot be inseted")
	ErrorParamNotValid                     = New(400, "param is not valid")
	ErrorProductItemDoesNotExists          = New(400, "product item does not exists")
	ErrorVariationDoesNotExists            = New(400, "variation does not exists")
	ErrorVariationDoesNotBelongsToCategory = New(400, "variation does not belongs to category")
	ErrorNeedJsonPayload                   = New(400, "need json payload")
)
